services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: exoseeker
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d exoseeker"]
      interval: 5s
      timeout: 3s
      retries: 15

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app:ro

  ingest:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
      api:
        condition: service_started
    volumes:
      - ./backend/app:/app:ro
      - ./data:/data:ro
    working_dir: /app
    command: python -m scripts.ingest_catalog
